version: "3.8"

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1003:1003"
    volumes:
      - ./src/uploads:/app/uploads
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
